### ISSUE TITLE
Feature: Integrate pre-commit

### ISSUE THREAD

**Issue by abes140377** [abes140377/yade-generator-cli#5]
Python Package:
https://pre-commit.com/#install

Linting Repos:
https://github.com/ansible/ansible-lint
https://github.com/antonbabenko/pre-commit-terraform

Example .pre-commit-config.yaml:
``` yaml
repos:
  # Terraform Checks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0  # wähle die gewünschte Version
    hooks:
      - id: terraform_fmt
        files: ^terraform/  # Nur im terraform/ Verzeichnis prüfen
      - id: terraform_validate
        files: ^terraform/

  # Ansible Checks
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.20.0  # wähle die gewünschte Version
    hooks:
      - id: ansible-lint
        files: ^ansible/  # Nur im ansible/ Verzeichnis prüfen
```
